version: '3'
services:
  nakama:
    image: skillzint/nakama:latest
    entrypoint:
      - "/bin/sh"
      - "-ecx"
      - >
          exec /nakama/nakama --name nakama1 --logger.level DEBUG --session.token_expiry_sec 7200
    restart: "no"
#    links:
#    depends_on:
#      - prometheus
    volumes:
      - ./:/nakama/data
    expose:
      - "7349"
      - "7350"
#      - "9100"
    ports:
      - "7349:7349"
      - "7350:7350"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7350/"]
      interval: 10s
      timeout: 5s
      retries: 5
#  prometheus:
#    image: prom/prometheus
#    entrypoint: /bin/sh -c
#    command: |
#      'sh -s <<EOF
#        cat > ./prometheus.yml <<EON
#      global:
#        scrape_interval:     15s
#        evaluation_interval: 15s
#
#      scrape_configs:
#        - job_name: prometheus
#          static_configs:
#          - targets: ['localhost:9090']
#
#        - job_name: nakama
#          metrics_path: /
#          static_configs:
#          - targets: ['nakama:9100']
#      EON
#      prometheus --config.file=./prometheus.yml
#      EOF'
#    ports:
#      - '9090:9090'

volumes:
  data:
